In [1]:
import numpy as np
import tensorflow as tf

In [2]:
13*13*32

5408

In [13]:
input_dim = 15
weight_scale=1e-2
hidden_dims = [12, 10, 5]
num_layers = len(hidden_dims) + 1
classes = 2

params = {'W' + str(y + 2) : np.random.normal(scale = weight_scale, size = (hidden_dims[y], hidden_dims[y + 1])) for y in range(num_layers - 2)}
params['W1'] = np.random.normal(0, weight_scale, (input_dim, hidden_dims[0]))
params['W' + str(num_layers)] = np.random.normal(0, weight_scale, (hidden_dims[-1], classes))
params['W1'] = 0
params

{'W1': 0, 'W2': array([[  1.66963761e-02,   8.67616756e-03,   4.71995429e-04,
           2.42536969e-03,   1.25587763e-02,  -3.39522562e-03,
          -3.55279672e-03,  -1.56154913e-03,   4.77257782e-04,
          -5.35544191e-03],
        [  4.53247754e-04,  -4.38985905e-03,   1.31588709e-02,
           1.42114379e-02,   1.22038568e-02,   7.94416019e-03,
           1.06379529e-02,  -1.38684050e-02,  -2.28728794e-02,
           1.40431301e-03],
        [ -4.60688459e-03,  -3.49468268e-03,   3.62854602e-03,
           9.66469766e-04,  -9.02920999e-03,   5.10710167e-04,
           1.15485590e-03,   1.02628905e-02,  -9.78693179e-03,
          -9.43913964e-04],
        [  6.10510430e-03,   1.44365503e-02,  -4.48797585e-03,
          -7.41626070e-03,  -2.72870479e-02,  -1.14306756e-02,
          -1.08831865e-02,   2.36532687e-03,   4.87721179e-03,
           1.01451157e-02],
        [  1.44236446e-02,   7.47447943e-03,  -4.46582361e-03,
          -2.27071313e-03,   1.21398275e-02,  -9.66562

In [62]:
k = 4 
i = 0 
x = np.arange(4).reshape((2,2))
y = np.zeros((4,2,2))
y[range(k),[i]*k,[0]*k] = x.flatten()
y

array([[[ 0.,  0.],
        [ 0.,  0.]],

       [[ 1.,  0.],
        [ 0.,  0.]],

       [[ 2.,  0.],
        [ 0.,  0.]],

       [[ 3.,  0.],
        [ 0.,  0.]]])

In [56]:
x = np.arange(24).reshape((3,2,2,2))
print(x)
print(x.reshape(6,2,2))
print(x.reshape(6,2,2).reshape((3,2,2,2)))

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]


 [[[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]]
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]

 [[20 21]
  [22 23]]]
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]


 [[[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]]


In [83]:
x = np.arange(12).reshape((2,2,3))
print(x)
x[:,1:2,0:2] += np.array([[[1,1]],[[1,1]]])
print(x[:,1:2,0:2])
print(x)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[[ 4  5]]

 [[10 11]]]
[[[ 0  1  2]
  [ 4  5  5]]

 [[ 6  7  8]
  [10 11 11]]]


In [ ]:
t = np.arange(9)
s = np.arange(3)
k = np.array([4,5,6])
temp = np.array([s,k])
#np.repeat(temp,2)
#np.repeat(s,k,2)
#np.dot(t,np.tile(s,3))
np.tile(temp,2)

In [109]:
dout = np.arange(96).reshape((3,2,4,4))
#print(dout)
#dout[:, :, 0, 0]
np.broadcast_to(dout[:, :, 0, 0].reshape(3,2,1,1), (3,2,8,8))

array([[[[ 0,  0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0,  0]],

        [[16, 16, 16, 16, 16, 16, 16, 16],
         [16, 16, 16, 16, 16, 16, 16, 16],
         [16, 16, 16, 16, 16, 16, 16, 16],
         [16, 16, 16, 16, 16, 16, 16, 16],
         [16, 16, 16, 16, 16, 16, 16, 16],
         [16, 16, 16, 16, 16, 16, 16, 16],
         [16, 16, 16, 16, 16, 16, 16, 16],
         [16, 16, 16, 16, 16, 16, 16, 16]]],


       [[[32, 32, 32, 32, 32, 32, 32, 32],
         [32, 32, 32, 32, 32, 32, 32, 32],
         [32, 32, 32, 32, 32, 32, 32, 32],
         [32, 32, 32, 32, 32, 32, 32, 32],
         [32, 32, 32, 32, 32, 32, 32, 32],
         [32, 32, 32, 32, 32, 32, 32, 32],
         [32, 32, 32, 32, 32, 32, 32, 32],
     

In [100]:
y = np.arange(6).reshape((2,3,1,1))
print(y)
np.broadcast_to(y, (2,3,2,2))

[[[[0]]

  [[1]]

  [[2]]]


 [[[3]]

  [[4]]

  [[5]]]]


array([[[[0, 0],
         [0, 0]],

        [[1, 1],
         [1, 1]],

        [[2, 2],
         [2, 2]]],


       [[[3, 3],
         [3, 3]],

        [[4, 4],
         [4, 4]],

        [[5, 5],
         [5, 5]]]])

In [98]:
x = np.arange(24).reshape((2,3,2,2))
print(x)
np.amax(x, axis = (2,3))
x == np.amax(x, axis = (2,3)).reshape((2,3,1,1))

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]

  [[ 8  9]
   [10 11]]]


 [[[12 13]
   [14 15]]

  [[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]]


array([[[[False, False],
         [False,  True]],

        [[False, False],
         [False,  True]],

        [[False, False],
         [False,  True]]],


       [[[False, False],
         [False,  True]],

        [[False, False],
         [False,  True]],

        [[False, False],
         [False,  True]]]], dtype=bool)

In [148]:
x = np.arange(120).reshape((2,3,4,5))

#trans_x = x.reshape((2*3,4,5)).reshape((3,2*4*5), order='F')

trans_x = np.transpose(x,(1,0,2,3)).reshape((3,-1))
#tt_x = trans_x.reshape(6,4,5,order='F').reshape((2,3,4,5))

x_mean_tr = np.mean(trans_x, axis=0)
x_mean = np.mean(x, axis=(0,2,3))
print(x_mean, x_mean_tr)
print(x)
print(trans_x)

[ 39.5  59.5  79.5] [ 20.  21.  22.  23.  24.  25.  26.  27.  28.  29.  30.  31.  32.  33.  34.
  35.  36.  37.  38.  39.  80.  81.  82.  83.  84.  85.  86.  87.  88.  89.
  90.  91.  92.  93.  94.  95.  96.  97.  98.  99.]
[[[[  0   1   2   3   4]
   [  5   6   7   8   9]
   [ 10  11  12  13  14]
   [ 15  16  17  18  19]]

  [[ 20  21  22  23  24]
   [ 25  26  27  28  29]
   [ 30  31  32  33  34]
   [ 35  36  37  38  39]]

  [[ 40  41  42  43  44]
   [ 45  46  47  48  49]
   [ 50  51  52  53  54]
   [ 55  56  57  58  59]]]


 [[[ 60  61  62  63  64]
   [ 65  66  67  68  69]
   [ 70  71  72  73  74]
   [ 75  76  77  78  79]]

  [[ 80  81  82  83  84]
   [ 85  86  87  88  89]
   [ 90  91  92  93  94]
   [ 95  96  97  98  99]]

  [[100 101 102 103 104]
   [105 106 107 108 109]
   [110 111 112 113 114]
   [115 116 117 118 119]]]]
[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75
   76  77  78

In [125]:
np.broadcast_to(np.array([1,2,3,1,2,3]).reshape((2,3,1,1)), (2,3,4,5)) 

array([[[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[2, 2, 2, 2, 2],
         [2, 2, 2, 2, 2],
         [2, 2, 2, 2, 2],
         [2, 2, 2, 2, 2]],

        [[3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3]]],


       [[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[2, 2, 2, 2, 2],
         [2, 2, 2, 2, 2],
         [2, 2, 2, 2, 2],
         [2, 2, 2, 2, 2]],

        [[3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3]]]])