In [2]:
import numpy as np
import tensorflow as tf

In [13]:
input_dim = 15
weight_scale=1e-2
hidden_dims = [12, 10, 5]
num_layers = len(hidden_dims) + 1
classes = 2

params = {'W' + str(y + 2) : np.random.normal(scale = weight_scale, size = (hidden_dims[y], hidden_dims[y + 1])) for y in range(num_layers - 2)}
params['W1'] = np.random.normal(0, weight_scale, (input_dim, hidden_dims[0]))
params['W' + str(num_layers)] = np.random.normal(0, weight_scale, (hidden_dims[-1], classes))
params['W1'] = 0
params

{'W1': 0, 'W2': array([[  1.66963761e-02,   8.67616756e-03,   4.71995429e-04,
           2.42536969e-03,   1.25587763e-02,  -3.39522562e-03,
          -3.55279672e-03,  -1.56154913e-03,   4.77257782e-04,
          -5.35544191e-03],
        [  4.53247754e-04,  -4.38985905e-03,   1.31588709e-02,
           1.42114379e-02,   1.22038568e-02,   7.94416019e-03,
           1.06379529e-02,  -1.38684050e-02,  -2.28728794e-02,
           1.40431301e-03],
        [ -4.60688459e-03,  -3.49468268e-03,   3.62854602e-03,
           9.66469766e-04,  -9.02920999e-03,   5.10710167e-04,
           1.15485590e-03,   1.02628905e-02,  -9.78693179e-03,
          -9.43913964e-04],
        [  6.10510430e-03,   1.44365503e-02,  -4.48797585e-03,
          -7.41626070e-03,  -2.72870479e-02,  -1.14306756e-02,
          -1.08831865e-02,   2.36532687e-03,   4.87721179e-03,
           1.01451157e-02],
        [  1.44236446e-02,   7.47447943e-03,  -4.46582361e-03,
          -2.27071313e-03,   1.21398275e-02,  -9.66562

In [62]:
k = 4 
i = 0 
x = np.arange(4).reshape((2,2))
y = np.zeros((4,2,2))
y[range(k),[i]*k,[0]*k] = x.flatten()
y

array([[[ 0.,  0.],
        [ 0.,  0.]],

       [[ 1.,  0.],
        [ 0.,  0.]],

       [[ 2.,  0.],
        [ 0.,  0.]],

       [[ 3.,  0.],
        [ 0.,  0.]]])

In [56]:
x = np.arange(24).reshape((3,2,2,2))
print(x)
print(x.reshape(6,2,2))
print(x.reshape(6,2,2).reshape((3,2,2,2)))

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]


 [[[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]]
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]

 [[20 21]
  [22 23]]]
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]


 [[[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]]


In [80]:
x = np.arange(12).reshape((2,2,3))
print(x)
print(x[:,1:2,0:2])

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[[ 3  4]]

 [[ 9 10]]]


In [38]:
t = np.arange(9)
s = np.arange(3)
k = np.array([4,5,6])
temp = np.array([s,k])
#np.repeat(temp,2)
#np.repeat(s,k,2)
#np.dot(t,np.tile(s,3))
np.tile(temp,2)

array([[0, 1, 2, 0, 1, 2],
       [4, 5, 6, 4, 5, 6]])

In [42]:
np.broadcast_to(t,(2,9))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8],
       [0, 1, 2, 3, 4, 5, 6, 7, 8]])